version: '3'

services:

  php:
    build: './docker/php'
    volumes:
      - '.:/var/www/html'
    ports:
      - '9000:9000' 

  mysql:
    image: 'mysql'
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql/volume:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'

  nginx:
    image: 'nginx:stable-alpine'
    ports:
      -  '80:80'
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
  
  phpmyadmin:
    image: 'phpmyadmin'
    ports:
      - '8080:80'
    environment:
      - 'PMA_ARBITRARY=1'
      - 'PMA_HOST=mysql'
      - 'PMA_USER=${DB_USERNAME}'
      - 'PMA_PASSWORD=${DB_PASSWORD}'
